artifact_location: file:///c:/Users/yasee/OneDrive/Desktop/Project/Machine%20Learning%20Projects/Rainy%20Prediction/mlruns/562568697270364510
creation_time: 1732508813108
experiment_id: '562568697270364510'
last_update_time: 1732508813108
lifecycle_stage: active
name: Rainy
